version: "3.9"

services:

  database:
    image: postgres:14-alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    build: .
    depends_on:
      - database
    environment:
      POSTGRES_SERVER: database
    env_file:
      - .env

volumes:
  dbdata:
